<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-MUEQ79FM" name="Test_Scenarios.TestMethods_HomePage" tests="5" failures="1" timestamp="2022-07-15T19:47:56 AEST" time="46.208" errors="0">
  <testcase name="NavigateToHomePage" time="0.067" classname="Test_Scenarios.TestMethods_HomePage"/>
  <system-out/>
  <testcase name="NavigateToShopPage" time="3.120" classname="Test_Scenarios.TestMethods_HomePage"/>
  <system-out/>
  <testcase name="BuyOneProduct" time="3.143" classname="Test_Scenarios.TestMethods_HomePage"/>
  <system-out/>
  <testcase name="BuyMultipleProducts" time="3.154" classname="Test_Scenarios.TestMethods_HomePage"/>
  <system-out/>
  <testcase name="NavigateToCartPage" time="36.724" classname="Test_Scenarios.TestMethods_HomePage">
    <failure type="java.lang.AssertionError" message="expected [Thanks] but found [Thanks Abi]">
      <![CDATA[java.lang.AssertionError: expected [Thanks] but found [Thanks Abi]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Planit.PageObjects.CheckOutPage.OrderPurchase(CheckOutPage.java:61)
at Test_Scenarios.TestMethods_HomePage.NavigateToCartPage(TestMethods_HomePage.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- NavigateToCartPage -->
  <system-out/>
</testsuite> <!-- Test_Scenarios.TestMethods_HomePage -->
